name: 'CD'

on:
  pull_request:
    branches: [ main ]

jobs:
  cd:
    runs-on: [ ubuntu-latest ]
    steps:
      - name:  나의 깃헙 코드를 깃헙 액션의 VM에 옮기는 작업 중 ...
        uses: actions/checkout@v4

      - name: 깃헙 액션의 VM에 자바 설치중 ...
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: dev yml 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application-dev.yml
        shell: bash

      - name: VM내의 (도커 컨테이너를 활용하여) MySQL 구동 시키기
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: trello
          mysql root password: ${{secrets.MYSQL_PASSWORD}}

      - name: 빌드 및 테스트 코드 돌리는중 ...
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: aws 배포용 yml 파일 생성
        run: |
          cd ./src/main/resources 
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./application-prod.yml
        shell: bash

      - name: aws 배포를 위한 application.yml 의 프로필을 prod로 바꿔주기
        run: |
          cd ./src/main/resources 
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: 다시 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew build -x test

      - name: 도커로 빌드시키고, hub에 올리기
        run: |
          docker login -u ${{secrets.DOCKER_HUB_ID}} -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker build -t ${{secrets.DOCKER_HUB_ID}}/${{secrets.DOCKER_HUB_REPO}} .
          docker push ${{secrets.DOCKER_HUB_ID}}/${{secrets.DOCKER_HUB_REPO}}

      - name: ec2에 docker-compose.yml 파일 복사시키기
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.AWS_HOST}}
          key: ${{secrets.AWS_KEY}}
          username: ubuntu
          source: ./docker-compose.yml
          target: ~/docker-compose.yml

      - name: executing remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOST}}
          key: ${{secrets.AWS_KEY}}
          username: ubuntu
          script: |
            sudo systemctl restart docker
            docker login -u ${{secrets.DOCKER_HUB_ID}} -p ${{secrets.DOCKER_HUB_TOKEN}}
            sudo docker pull ${{secrets.DOCKER_HUB_ID}}/${{secrets.DOCKER_HUB_REPO}}            
            cd ~/docker-compose.yml
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f

      - name: 오류명 상세히 알려줌
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test
